#server:
#  port: 8081
#
#spring:
# cloud:
#  gateway:
#   server:
#    webflux:
#      routes:
#        - id: auth-service
#          uri: http://localhost:8086
#          predicates:
#            - Path=/auth/**,/trainers/**,/visitor/**
#
#        - id: MEMBER-SERVICE
#          uri: http://localhost:8082
#          predicates:
#            - Path=/members/**,/bookings/**,/payments/**,/classes/**


#use it for local
#server:
# port: 8081
#
#spring:
# application:
#  name: api-gateway	
#
# cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service 
#          predicates:
#            - Path=/auth/**,/trainers/**,/visitor/**
#
#        - id: member-service
#          uri: lb://MEMBER-SERVICE
#          predicates:
#            - Path=/members/**,/bookings/**,/payments/**,/classes/**,
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka 						

#to upload project on Railway i am doing below changes

server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://fitness-auth-service-repo-production.up.railway.app/
          predicates:
            - Path=/auth/**,/trainers/**,/visitor/**

        - id: member-service
          uri: https://fitness-member-service-repo-production.up.railway.app/
          predicates:
           - Path=/members/**,/bookings/**,/payments/**,/classes/**,

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
#  instance:
#    hostname: ${EUREKA_INSTANCE_HOSTNAME}
#    non-secure-port-enabled: false
#    secure-port-enabled: true
#    secure-port: 443
#    status-page-url: https://${EUREKA_INSTANCE_HOSTNAME}/actuator/info
#    health-check-url: https://${EUREKA_INSTANCE_HOSTNAME}/actuator/health
#    home-page-url: https://${EUREKA_INSTANCE_HOSTNAME}